### ISSUE TITLE
implement Dropdown in place of checkboxes

### ISSUE THREAD

**Issue by tushartiwari7** [tushartiwari7/travelGuide#1]
### Fork the [repo](https://github.com/tushartiwari7/travelGuide) and setup project on localhost
* make sure functionality remains same and everything works.
* ping me on  [twitter](https://twitter.com/tushartiwari_me) if need any help regarding this.

**Comment by vrouilhac** [comment]
Hi, I'd like to help you with this. What do you mean by checkboxes? Do you actually want to replace the button with a dropdown menu ?

**Comment by tushartiwari7** [comment]
I'm so sorry I pushed this issue to a different Repository.
Actually, I want to do the same thing in [language-translator](https://github.com/tushartiwari7/language-translator) repo.
